name: DiscordAuthentication
main: com.johnymuffin.beta.discordauth.DiscordAuthentication
author: JohnyMuffin
version: 1.1.3
depend: [DiscordCore]
commands:
  discordauth:
    description: Basic DiscordAuth commands
    usage: /<command>